# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Carlos Peix"
subtitle: "Agile Consultant"
name: "Carlos Peix"
email: carlos.peix@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  En este sitio publico mis experiencias como consultor en diseño organizacional, liderazgo y agilidad de negocios.
  In this site I share my experiences as a consultant in organizational design, leadership and business agility.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. https://example.com
twitter_username: carlospeix
github_username:  carlospeix

lang: sp
show_excerpts: true
locale: "es"

# Build settings
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-include-cache

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-22967558-1"
    anonymize_ip: false

category_archive:
  type: jekyll-archives
  path: /categories/
tag_archive:
  type: jekyll-archives
  path: /tags/
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

defaults:
  - 
    scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author: "Carlos Peix"
      permalink: "/:year/:month/:title/"
      excerpt_separator: <!--more-->
      show_date: true
      read_time: true
      related: true
  - 
    scope:
      path: ""
      type: "pages"
    values:
      layout: "single"

header_pages:
  - categories.md
  - tags.md
  - about.md

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
